---
title: "R Notebook"
---

```{r echo=F, include=F, warning=FALSE}
library(httr)
library(rvest)
library(purrr)
library(stringr)
library(magrittr)
library(dplyr)
library(knitr)

# source only if needed
tryCatch(CorporateSourced(), error = function(e) source("Corporate.R"))

# set sys
# Sys.setlocale("LC_TIME","English")

```

```{r echo=F, include=F}
# init table
initPriceTable <-  function() {
  cols <- c("vendor",
            "date",
            "week",
            "day",
            "fuel",
            "price",
            "week_rank",
            "origin")
  table <- data.frame(matrix(nrow = 0, ncol = length(cols)))
  colnames(table)=cols
  table
}

# load datalog
dataTable <- read.csv("data.csv")
dataTable$X = NULL
dataTable$date %<>% as.Date

# UTILITIES
# get current date
today <- Sys.Date() %>% as.Date

# Rounding
roundTo  <- function(precision) {
    # via Closure
    function(x) {
        fctr = 10 ^ precision
        round(x * fctr) / fctr
    }
}

round1 <- roundTo(1)
round2 <- roundTo(2)
round3 <- roundTo(3)

# update into is a closure function
updatePriceInto <- function(table) {
  # as a closure, to check against provided table
  # does not mutate provided table (has to be 'rbind' to include in data)
  function(vendor, date, fuel, price, origin) {
    vendorNow <- vendor # warning, has to provide new var, table$vendor == vendor would not work in filter
    fuelNow <- fuel
    tableNow <- filter(table, table$vendor==vendorNow, table$fuel==fuelNow)  
    dataNow <- data.frame(vendor,
                          date,
                          week = format(date,"%Y/w%W"),
                          day = weekdays(date),
                          fuel,
                          price,
                          week_rank = format(date-1,"%Y%W"),
                          origin)

    if (date %in% tableNow$date) {
      currentPrices <- tableNow %>% filter(.,.$date==date,.$fuel==fuel) %>% .$price
      if (price %in% currentPrices) {
        print(paste0("[Warning] Zaznam jiz existuje: ", date," > ", fuel, " : ", price, " /", origin, "/"))
        NULL
      } else {
        # TODO d-1 zmena....
        print(paste("[Attention] zmena existujici ceny", date, fuel, price))
        NULL
      }
    } else {
      print(paste(date, "Nova cena", fuel, ":", price))
      dataNow
    }
  }
}

# ADJUST DATA
addMissingData <- function(vendor, date, fuel, price, origin = "manual_input", export = F) {

  missingData <- updatePriceInto(dataTable)

  dataTable %<>%  rbind(.,missingData(vendor,
                                      date,
                                      fuel,
                                      price,
                                      origin))
  dataTable %<>% .[rev(order(.$date)),]
  if (export) dataTable %>% write.csv(.,"data.csv")
  dataTable
}

comment <- function() {
  ## DEV block

  addMissingData(vendor = "AXIGON",
                 date = as.Date("2019-11-26"),
                 fuel = "Diesel",
                 price = 25.28,
                 export = T)


}
# check proxy/connection
proxyValidation()
```


## AXIGON
```{r}
URL_AXI <- "https://www.axigon.cz"

# get page
pgAxi <- read_html(GET(URL_AXI))
```

```{r echo=F}
# slurp price from web
price <- html_nodes(pgAxi, "div.hero__remark") %>%
  html_text %>%
  str_extract(.,"\\d....") %>%
  str_replace(.,"[,]","\\.") %>%
  as.double


# update and save
priceUpdate <- updatePriceInto(dataTable)
dataTable %<>% rbind(.,priceUpdate(vendor = "AXIGON",
                                   date = today,
                                   fuel = "Diesel",
                                   price = price,
                                   origin = "webslurp"))

```

```{r eval = FALSE, include = FALSE}
# ADD external data
# TODO net develop, one time usage
# TODO fn to set correct form for rbind
# TODO to check what is in data during import

library(readxl)
dataNow <- read_excel("external/bslurp.xlsx", sheet = "Diesel")
dataNow %<>% select(.,c(Date,`Axigon List price`))
dataNow %<>% `colnames<-`(.,c("date", "price"))
dataNow$date %<>%  as.Date
dataNow$price %<>% round2
dataNow$day = weekdays(dataNow$date)
dataNow$vendor = "AXIGON"
dataNow$fuel = "Diesel"
dataNow$week_rank = format(dataNow$date,"%Y%W")
dataNow$week = week = format(dataNow$date,"%Y/w%W")
dataNow$origin = "importXLS"

newDataTable <- rbind(dataTable,dataNow)
newDataTable %>% .[rev(order(.$date)),]
#newDataTable %>% write.csv(.,"data.csv")
```


```{r echo=F,include=FALSE}
comment <- function() {
  # dev block

  rm(list = ls())
  dataTable

}
```

```{r eval=FALSE, include=FALSE}
## ERNEKS
URL_ERN <- "http://www.erneks.cz/tankovaci-karta/shell-fix"

pgErn <- read_html(GET(URL_ERN))
```

```{r eval=FALSE, include=FALSE}
html_nodes(pgErn, "div.AREA_advantages")
```

## TANK ONO
```{r}
## Tank ONO
URL_TONO <- "http://m.tank-ono.cz/cz/index.php?page=cenik"
pgTono <- read_html(GET(URL_TONO))

```

```{r echo=F, warning=FALSE}
extractDivItems <- function(div) {
  # Creates closure around div class name
  # takes min and max rows index for result
  function(rowMin, rowMax) {
    result <- html_nodes(pgTono, div) %>%
           html_text %>%
           .[rowMax:rowMin] %>%
           # remove new-line, return, spaces
           gsub("[\r\n ]", "", .) %>%
           data.frame %>%
           mutate_all(as.character)
    result
  }
}

tonoPrices <- extractDivItems("div.divprice")
tonoGNames <- extractDivItems("div.divprgw")
tonoDNames <- extractDivItems("div.divprbw")

tonoPL_withVAT <- bind_cols(bind_rows(tonoGNames(1,4), tonoDNames(1,2)),
                    bind_rows(tonoPrices(1,4),tonoPrices(5,6)))
tonoPL <- tonoPL_withVAT

tonoPL %<>% `colnames<-`(.,c("fuel","price"))
tonoPL$price %<>% as.double
tonoPL$price <- round2(tonoPL$price / 121)
tonoPL$vendor = "TankOno"
tonoPL$date = today
tonoPL$origin = "webslurp"
target <- c("DIESEL", "NATURAL98", "NATURAL95")
tonoPL %<>% filter(., fuel %in% target)

# TODO join the main dataTable
tonoUpdate <- updatePriceInto(dataTable)

for(i in 1:nrow(tonoPL)) {
  item = tonoPL[i,]
  dataTable <- rbind(dataTable, tonoUpdate(vendor = "TankOno",
                                           date = item$date,
                                           fuel = item$fuel,
                                           price = item$price,
                                           origin = "webslurp"))
}

kable(tonoPL_withVAT %<>% `colnames<-`(c("Fuel","P_w_VAT")))

comment <-  function() {
  #Dev block=
  "NATURAL95" %in% tonoPL$fuel
  "NATURAL98" %in% tonoPL$fuel
  (tonoPL %>% filter(., .$fuel=="DIESEL"))
  (tonoPL %>% filter(., .$fuel=="NATURAL98"))
  
}
```

## Twin Trans
```{r echo=F}
URL_TTRANS <- "http://www.twintrans.cz"
pgTtrans<- read_html(GET(URL_TTRANS))

```

```{r echo=F}
priceList <- html_nodes(pgTtrans, "tr") %>% html_text
priceListJET <- priceList[2] %>%
                strsplit(., "[\n]") %>%
                .[[1]] %>%
                noquote %>%
                gsub("[ ]", "", .) %>% gsub("KÄ/l", "", .) %>% gsub(",",".",.)

# rbind dataTable
if (priceListJET[1] == "JETA-1" && priceListJET[3] == "bezSPD(sazba9.95)") {
  jetPrice <- as.double(priceListJET[2])
  update <- updatePriceInto(dataTable)
  dataTable %<>% rbind(., update(vendor = "TwinTrans",
                                date = today,
                                fuel = "JET",
                                price = jetPrice,
                                origin = "webslurp"))
  
} else {
  "ERROR, JET conditions does not match"
}

comment <- function() {
  ## Dev block
  update <- updatePriceInto(dataTable)
  update(vendor = "TwinTrans",
         date = today,
         fuel = "JET",
         price = jetPrice,
         origin = "webslurp")
  table <- dataTable 
  table <- filter(table, table$vendor=="TwinTrans")
  table$date
  (today %in% table$date)
}

```
## DATA
```{r echo=F}
dataTable %<>% .[rev(order(.$date,.$vendor)),]
knitr::kable(dataTable %>% head(.,21))

# data Serialization
dataTable %>% write.csv(.,"data.csv")
#dataTable %>% head(., 5) %>% View
```
