---
title: "Spot On"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
library(rmarkdown)
library(magrittr)
library(dplyr)
library(tidyverse)
library(knitr)
knitr::opts_chunk$set(fig.align = "left")


# for CZ chars
if (.Platform$OS.type == 'windows') {
  Sys.setlocale(category = 'LC_ALL','English_United States.1250')
} else {
  Sys.setlocale(category = 'LC_ALL','en_US.UTF-8')
}
```

```{r date, echo=FALSE}
dateNow <- Sys.Date()
Today <- strftime(Sys.Date(), format = "%Y-%m-%d")
The_Week <- strftime(dateNow, format = "%Y/w%V")
dfDate <- data.frame(Today, The_Week)
kable(dfDate,
      col.names = c("Today's", "This Week"),
      align = "r")
```


```{r load-data, include=FALSE}
v.raw <- read.csv("data.csv")
v.raw$X = NULL
v <- v.raw %>%
 select(., "vendor", "origin", "week", "date", "day", "fuel", "price")
```

### Tank Ono

```{r tono, include=FALSE}
tono.diesel <- v %>% filter(. , .$vendor == "TankOno" & .$fuel == "DIESEL")
tono.diesel$PriceVAT = round(tono.diesel$price * 1.21, 1)
tono.ba95 <- v %>% filter(. , .$vendor == "TankOno" & .$fuel == "NATURAL95")
tono.ba95$PriceVAT = round(tono.ba95$price * 1.21, 1)
```

> Gasoline BA95

```{r tono-ba95, echo=F, fig.width = 9, fig.height = 5 }
kable(head(tono.ba95, 7))
ggplot(data = head(tono.ba95, 30),
       aes(week, PriceVAT,
           label = PriceVAT)
       ) + geom_text(aes(label=PriceVAT),
                     hjust=-0.2, vjust=1
                     ) + geom_line() + geom_point()
```

> Diesel

```{r tono-diesel, echo=F, fig.width = 9, fig.height = 5 }
kable(head(tono.diesel, 7))

ggplot(data = head(tono.diesel, 30),
       aes(week, PriceVAT,
           label = PriceVAT)) + geom_text(aes(label=PriceVAT), hjust=-0.2, vjust=1) + geom_line() + geom_point()
```

### Axigon
```{r axigon, include=FALSE}
axigon.diesel <- v %>% filter(. , .$vendor == "AXIGON" & .$fuel == "Diesel")
axigon.diesel$PriceVAT = round(axigon.diesel$price * 1.21, 1)
axigon.diesel$price %<>% round(., 1)
```

> Diesel

```{r axigon-diesel, echo=F, fig.width = 9, fig.height = 5 }
kable(head(axigon.diesel, 7))

ggplot(data = head(axigon.diesel, 30),
       aes(week, price,
           label = price)) + geom_text(aes(label=price), hjust=-0.2, vjust=1) + geom_line() + geom_point()
```

### UIC
```{r uic, include=FALSE}
url <- "https://www.unipetrolrpa.cz/CS/NabidkaProduktu/rafinerske-produkty/uic.csv"

# read csv, select cols
uic.table  <- read.csv(url, sep = ";", encoding = "UTF-8") %>% select(., DATUM, PALIVO, UIC) 

# rename & format cols
uic.table %<>% `colnames<-`(., c("date", "fuel", "price"))
uic.table$date %<>% as.Date

# add week
uic.table$week = format(uic.table$date, "%Y/w%W")

# add day
uic.table$day = weekdays(uic.table$date)

# add origins
uic.table$vendor = "UIC"
uic.table$origin = "web/csv"

# rearange
uic.table %<>% select(vendor, origin, week, date, day, fuel, price)

# convert and add price(lit) % priceVat
uic.table$price = round(uic.table$price / 1000, 1)
uic.table$priceVAT = round(uic.table$price * 1.21, 1)

# set fuel specific tables
uic.diesel  <- uic.table %>% filter(grepl("Motor", fuel))
uic.ba95  <- uic.table %>% filter(., .$fuel == "Benzin BA95")
```

> Diesel

```{r uic-diesel, echo=F, fig.width = 9, fig.height = 5 }
kable(head(uic.diesel, 14))

ggplot(data = head(uic.diesel, 33),
       aes(week, price,
           label = price)) + geom_text(aes(label=price), hjust=-0.2, vjust=1) + geom_line() + geom_point()
```

> Gasoline BA95

```{r uic-ba95, echo=F, fig.width = 9, fig.height = 5 }
kable(head(uic.ba95, 14))

ggplot(data = head(uic.ba95, 33),
       aes(week, price,
           label = price)) + geom_text(aes(label=price), hjust=-0.2, vjust=1) + geom_line() + geom_point()
```

```{r dev-block, include=F}
print("dev block")
kable(head(uic.table, 14))
uic.table %>% head(., 14)
```
